server {
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(png|jpg|jpeg|gif|webp|svg|ico|css|js|woff|woff2|ttf|eot)$ {
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        internal;
    }
}